name: TerritorialityMC
version: ${project.version}
main: co.superstuff.TerritorialityMCPlugin
api-version: '1.20'
authors: [David Waster]
description: A plugin to claim territories and fight for them.
commands:
  tmc:
    description: Use the Territoriality MC plugin command
    usage: /tmc <command>
permissions:
  territorialitymc.register:
    description: Allows the user register as landowner
    default: op